spring:
  application:
    name: newsapi
  datasource:
    url: jdbc:postgresql://db.tlvefiyenmdpnqrbadjm.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  servlet:
    context-path: "/api/v1"

openrouter:
  apiKey: ${OPENROUTER_API_KEY}
  modelId: x-ai/grok-4-fast:free

